### ISSUE TITLE
Predication's label should be binary?

### ISSUE THREAD

**Issue by nevillelyh** [spotify/noether#2]
Right now we have `case class Prediction(label: Int, score: Double)` where `label` is an `Int` but in practice it can only be 1 and 0. I wonder if it's better to encode it with a binary ADT?

**Comment by richwhitjr** [comment]
Some of the names may have to be rethought to better match the case class with the aggregator.  For example the confusion matrix aggregator could work in the multi-class setting but when used to compute AUC only the binary case makes sense.

Maybe each aggregator should be paired with a input case class that has similar names to avoid confusion?  AUCAggregator takes a AUCPrediction with a binary label?  ConfusionMatrix can take a ConfusionMatrixPrediction and extended to work in higher dimensions?

**Comment by nevillelyh** [comment]
Or we can parameterize `Prediction` and specialize it on each aggregator?

**Comment by richwhitjr** [comment]
Makes sense.  May have to parameterize both sides to handle other cases likes logloss also.
https://github.com/spotify/noether/blob/master/core/src/main/scala/com/spotify/noether/LogLoss.scala#L22

`case class Prediction[T, S](scores: S, label: T)`

**Comment by richwhitjr** [comment]
PR here around this change.  https://github.com/spotify/noether/pull/6

**Comment by richwhitjr** [comment]
#6 merged.
